### ISSUE TITLE
How to use with the original Colorhug?

### ISSUE THREAD

**Issue by 0rAX0** [hughski/colorhug-client#16]
Hey,

I have an original Colorhug device which I bought way too early (even before the strap was introduced). Anyways, I cleared the dust off of mine today and tried to use it to calibrate my new monitor but I discovered that the client is asking for Colorhug2, did you drop support for the 1 or how can I use it now?

I installed the package on Archlinux btw.

**Comment by hughsie** [comment]
I think it should just work, what message do you get from colorhug-client --verbose?

**Comment by 0rAX0** [comment]
Hmm, this is weird. The Arch package doesn't come with a colorhug-client executable! Here's the list of executables it provides:

- colorhug-backlight  
- colorhug-ccmx       
- colorhug-cmd        
- colorhug-flash     
- colorhug-refresh 

Executing from the app list opens this, which doesn't detect the CH1
![Screenshot (3)](https://user-images.githubusercontent.com/1044370/90314590-c2dbae80-df0c-11ea-8551-4b8a4f997565.png)


(I have calibrated in Windows using DisplayCal anyway)

**Comment by ArchangeGabriel** [comment]
`colorhug-client` is `colorhug-cmd` AFAIK. What you opened is `colorhug-refresh`.

**Comment by hughsie** [comment]
> What you opened is colorhug-refresh

Indeed! The colorhug-refresh uses hardware on the CH2 which didn't exist on the CH1 -- you just can't get the data out of the sensor of the CH1 to get the display refresh information. I think you probably want to use DisplayCAL to calibrate these days anyway: https://displaycal.net/
